"use client";

import { Download, Eye } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Table } from "@/components/ui/Table";
import { formatDateTime } from "@/lib/utils";
import { REPORT_FORMAT_BADGE_MAP } from "@/lib/mock/vmElectionReportsMockData";

export function RecentReportsTable({ reports, isLoading, page, pageSize, totalCount, onPageChange, emptyMessage = "No reports found." }) {
  const columns = [
    { key: "name", header: "Report Name", render: (r) => (
      <div>
        <p className="font-medium text-ink">{r.name}</p>
        <p className="text-xs text-ink-subtle">{r.election}</p>
      </div>
    ) },
    { key: "type", header: "Type", render: (r) => <span className="text-ink">{r.type}</span> },
    { key: "generatedBy", header: "Generated By", render: (r) => <span className="text-ink">{r.generatedByName}</span> },
    { key: "generatedOn", header: "Generated On", render: (r) => <span className="text-ink">{formatDateTime(r.generatedOn)}</span> },
    { key: "format", header: "Format", render: (r) => <Badge variant={REPORT_FORMAT_BADGE_MAP[r.format] ?? "info"}>{r.format}</Badge> },
    { key: "actions", header: "Actions", render: (r) => (
      <div className="flex items-center gap-1">
        <button type="button" className="flex h-8 w-8 items-center justify-center rounded-md text-ink-subtle hover:bg-surface-canvas" aria-label="View report">
          <Eye className="h-4 w-4" />
        </button>
        <button type="button" className="flex h-8 w-8 items-center justify-center rounded-md text-ink-subtle hover:bg-surface-canvas" aria-label="Download report">
          <Download className="h-4 w-4" />
        </button>
      </div>
    ) },
  ];

  return (
    <Table
      columns={columns} data={reports} isLoading={isLoading}
      emptyMessage={emptyMessage}
      pagination={{ page, pageSize, totalCount, onPageChange }}
    />
  );
}
