"use client";

import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { Download, MoreHorizontal, Eye, Share2, Trash2 } from "lucide-react";
import { Table } from "@/components/ui/Table";
import { Badge } from "@/components/ui/Badge";

const FORMAT_VARIANT = { PDF: "danger", Excel: "success" };

const menuItemClass =
  "flex w-full items-center gap-2 rounded px-2.5 py-2 text-sm text-ink-muted outline-none transition-colors hover:bg-surface-canvas hover:text-ink focus:bg-surface-canvas cursor-pointer";

function RowActionsMenu({ row, onDownload, onView, onShare, onDelete }) {
  return (
    <div className="flex items-center justify-end gap-1">
      <button type="button" onClick={() => onDownload?.(row)} className="flex h-8 w-8 items-center justify-center rounded-md border border-border text-ink-subtle hover:bg-surface-canvas" aria-label="Download">
        <Download className="h-4 w-4" />
      </button>
      <DropdownMenu.Root>
        <DropdownMenu.Trigger asChild>
          <button type="button" className="flex h-8 w-8 items-center justify-center rounded-md border border-border text-ink-subtle hover:bg-surface-canvas" aria-label="More actions">
            <MoreHorizontal className="h-4 w-4" />
          </button>
        </DropdownMenu.Trigger>
        <DropdownMenu.Portal>
          <DropdownMenu.Content align="end" sideOffset={6} className="z-50 w-48 rounded-md border border-border bg-white p-1.5 shadow-elevated animate-fade-in">
            <DropdownMenu.Item className={menuItemClass} onSelect={() => onView?.(row)}><Eye className="h-4 w-4" /> View</DropdownMenu.Item>
            <DropdownMenu.Item className={menuItemClass} onSelect={() => onShare?.(row)}><Share2 className="h-4 w-4" /> Share</DropdownMenu.Item>
            <DropdownMenu.Separator className="my-1 h-px bg-border" />
            <DropdownMenu.Item className={`${menuItemClass} text-danger-600 hover:text-danger-600`} onSelect={() => onDelete?.(row)}><Trash2 className="h-4 w-4" /> Delete</DropdownMenu.Item>
          </DropdownMenu.Content>
        </DropdownMenu.Portal>
      </DropdownMenu.Root>
    </div>
  );
}

export function ReportSummaryTable({ reports, isLoading, pagination, onDownload, onView, onShare, onDelete }) {
  const columns = [
    { key: "name", header: "Report Name", render: (row) => <span className="font-medium text-ink">{row.name}</span> },
    { key: "description", header: "Description", render: (row) => <span className="text-ink-muted">{row.description}</span> },
    {
      key: "generatedOn", header: "Generated On",
      render: (row) => (
        <span className="text-ink-muted">
          {new Date(row.generatedOn).toLocaleString("en-IN", { day: "numeric", month: "short", year: "numeric", hour: "numeric", minute: "2-digit" })}
        </span>
      ),
    },
    { key: "generatedBy", header: "Generated By", render: (row) => <span className="text-ink-muted">{row.generatedBy}</span> },
    { key: "format", header: "Format", render: (row) => <Badge variant={FORMAT_VARIANT[row.format] ?? "default"}>{row.format}</Badge> },
    {
      key: "actions", header: "Action", cellClassName: "text-right", className: "text-right",
      render: (row) => <RowActionsMenu row={row} onDownload={onDownload} onView={onView} onShare={onShare} onDelete={onDelete} />,
    },
  ];

  return (
    <div className="rounded-lg border border-border bg-white shadow-card">
      <div className="px-4 pt-4 pb-1">
        <h3 className="text-sm font-semibold text-ink">Report Summary</h3>
      </div>
      <Table
        columns={columns} data={reports} isLoading={isLoading} getRowId={(row) => row.id}
        className="rounded-none border-0 shadow-none" pagination={pagination}
        emptyMessage="No reports generated yet." emptyDescription="Once reports are generated, they'll show up here."
      />
    </div>
  );
}
