
export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  BISHOP: "BISHOP",
  DIOCESE_ADMIN: "DIOCESE_ADMIN",
  PASTOR: "PASTOR",
  CHURCH_SECRETARY: "CHURCH_SECRETARY",
  TREASURER: "TREASURER",
  MINISTRY_LEADER: "MINISTRY_LEADER",
  MEMBER: "MEMBER",
  VISITOR: "VISITOR",
};

export const ROLE_LABELS = {
  SUPER_ADMIN: "Super Admin",
  BISHOP: "Bishop",
  DIOCESE_ADMIN: "Diocese Admin",
  PASTOR: "Pastor",
  CHURCH_SECRETARY: "Church Secretary",
  TREASURER: "Treasurer",
  MINISTRY_LEADER: "Ministry Leader",
  MEMBER: "Member",
  VISITOR: "Visitor",
};

export const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.BISHOP, ROLES.DIOCESE_ADMIN];
export const CHURCH_STAFF_ROLES = [...ADMIN_ROLES, ROLES.PASTOR, ROLES.CHURCH_SECRETARY];
export const FINANCE_ROLES = [...ADMIN_ROLES, ROLES.PASTOR, ROLES.TREASURER];
export const MINISTRY_MANAGE_ROLES = [...ADMIN_ROLES, ROLES.PASTOR, ROLES.MINISTRY_LEADER];
