"use client";

import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { Eye, Download, MoreVertical, ChevronRight } from "lucide-react";
import { Table } from "@/components/ui/Table";
import { formatDate } from "@/lib/utils";

const itemClass =
  "flex w-full items-center gap-2 rounded px-2.5 py-2 text-sm text-ink-muted outline-none transition-colors hover:bg-surface-canvas hover:text-ink focus:bg-surface-canvas cursor-pointer";

export function RecentReportsTable({ reports = [] }) {
  const columns = [
    { key: "name", header: "Report Name", render: (row) => <span className="font-medium text-ink">{row.name}</span> },
    { key: "category", header: "Category", render: (row) => <span className="text-ink-muted">{row.category}</span> },
    {
      key: "generatedOn", header: "Generated On",
      render: (row) => <span className="text-ink-muted">{formatDate(row.generatedOn)} {row.generatedTime}</span>,
    },
    { key: "generatedBy", header: "Generated By", render: (row) => <span className="text-ink-muted">{row.generatedBy}</span> },
    {
      key: "actions", header: "Actions", cellClassName: "text-right", className: "text-right",
      render: (row) => (
        <div className="flex items-center justify-end gap-1.5">
          <button type="button" className="flex h-8 w-8 items-center justify-center rounded-md border border-border text-ink-subtle hover:bg-surface-canvas" aria-label={`View ${row.name}`}>
            <Eye className="h-4 w-4" />
          </button>
          <button type="button" className="flex h-8 w-8 items-center justify-center rounded-md border border-border text-ink-subtle hover:bg-surface-canvas" aria-label={`Download ${row.name}`}>
            <Download className="h-4 w-4" />
          </button>
          <DropdownMenu.Root>
            <DropdownMenu.Trigger asChild>
              <button type="button" onClick={(e) => e.stopPropagation()} className="flex h-8 w-8 items-center justify-center rounded-md border border-border text-ink-subtle hover:bg-surface-canvas" aria-label={`More actions for ${row.name}`}>
                <MoreVertical className="h-4 w-4" />
              </button>
            </DropdownMenu.Trigger>
            <DropdownMenu.Portal>
              <DropdownMenu.Content align="end" sideOffset={6} className="z-50 w-40 rounded-md border border-border bg-white p-1.5 shadow-elevated animate-fade-in">
                <DropdownMenu.Item className={itemClass}>Share</DropdownMenu.Item>
                <DropdownMenu.Item className={itemClass}>Schedule</DropdownMenu.Item>
                <DropdownMenu.Separator className="my-1 h-px bg-border" />
                <DropdownMenu.Item className={`${itemClass} text-danger-600 hover:text-danger-600`}>Delete</DropdownMenu.Item>
              </DropdownMenu.Content>
            </DropdownMenu.Portal>
          </DropdownMenu.Root>
        </div>
      ),
    },
  ];

  return (
    <div className="rounded-lg border border-border bg-white shadow-card">
      <div className="flex items-center justify-between border-b border-border px-4 py-3">
        <h3 className="text-base font-semibold text-ink">Recent Reports</h3>
        <button type="button" className="flex items-center gap-1 text-xs font-medium text-interactive-500 hover:underline">
          View All Reports <ChevronRight className="h-3.5 w-3.5" />
        </button>
      </div>
      <Table columns={columns} data={reports} getRowId={(row) => row.name} className="rounded-none border-0 shadow-none" />
    </div>
  );
}
